trigger:
  - main
pool:
  vmImage: "ubuntu-latest"
jobs:
  job: "NPM Install and Build"
  steps:
   - task: AzureStaticWebApp@0
    inputs:
      app_location: './build' # App source code path relative to cwd
      cwd: '$(System.DefaultWorkingDirectory)' # Working directory - optional
      azure_static_web_apps_api_token: $(deployment_token)