trigger:
  - main
pool:
  vmImage: "ubuntu-latest"
jobs:
  - job: "publish_azure_static_app"
    steps:
      - task: AzureStaticWebApp@0
        inputs:
          app_location: "./build" # App source code path relative to cwd
          cwd: "$(System.DefaultWorkingDirectory)"
          azure_static_web_apps_api_token: $(deployment_token)
