trigger:
  - main
pool:
  vmImage: "ubuntu-latest"
jobs:
  job: "NPM Install and Build"
  steps:
    // Install Node v16
    - task: NodeTool@0
      inputs:
        versionSpec: "16.x"
      displayName: "Install NodeJS v16"
    // Install packages
    - script: |
        npm install
      displayName: "NPM Install"
    // Build
    - script: |
        npm run build
      displayName: "NPM Build"